### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by kirchenn** [thomas-lowry/status-annotations#2]
Hi! 
It's not an issue, but the fastest way to reach you I could get to.

If it were possible to change the placement of status — we have rather wide screens (1920 pixels), and small statuses on the right get lost and remain unnoticed, I believe if they were at the beginning of a frame, they would become more noticeable. 

So, as I am not a coder myself, it is not an option for me to customize the plugin myself, and I thought it would be fine to just put this idea out there.

**Comment by thomas-lowry** [comment]
Hey, it’s a pretty easy customization to make, happy to make a one off version for you with this change, but probably won’t do this on the production version (I made the decision to put them on the right so that at certain zoom levels they don’t conflict with the name of the frame, which gets rendered at the same font size at different view levels). 

Let me know if that would be helpful.
